version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.4
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
  - dependency-name: "@ckeditor/ckeditor5-widget"
    versions:
    - 27.0.0
  - dependency-name: "@ckeditor/ckeditor5-paste-from-office"
    versions:
    - 27.0.0
  - dependency-name: "@ckeditor/ckeditor5-font"
    versions:
    - 27.0.0
  - dependency-name: "@ckeditor/ckeditor5-media-embed"
    versions:
    - 27.0.0
  - dependency-name: "@ckeditor/ckeditor5-image"
    versions:
    - 27.0.0
  - dependency-name: "@ckeditor/ckeditor5-markdown-gfm"
    versions:
    - 25.0.0
    - 26.0.0
    - 27.0.0
  - dependency-name: "@ckeditor/ckeditor5-ui"
    versions:
    - 24.0.0
    - 25.0.0
    - 26.0.0
    - 27.0.0
  - dependency-name: "@ckeditor/ckeditor5-utils"
    versions:
    - 24.0.0
    - 25.0.0
    - 26.0.0
    - 27.0.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@ckeditor/ckeditor5-engine"
    versions:
    - 24.0.0
    - 25.0.0
    - 26.0.0
  - dependency-name: "@ckeditor/ckeditor5-list"
    versions:
    - 25.0.0
    - 26.0.0
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: jquery
    versions:
    - 3.5.1
